spring.application.name=train-service
server.port=8082

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/train_db
spring.datasource.username=postgres
spring.datasource.password=redocmi
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
